config/routes.rb
Rails.application.routes.draw do
  
  resources :companies
  

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, presence: true,
  length: { in: 2..35 },
  uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  def index
    @companies = Company.all
  end
  
  def show
    @company = Company.find(params[:id])
  end
  
  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(company_params)
    
    if @company.save
      redirect_to @company
    else
      render 'new'
    end
  end
  
  def edit
    @company = Company.find(params[:id])
  end
  
  def update
    @company = Company.find(params[:id])
    
    if @company.update(company_params)
      redirect_to @company
    else
      render 'edit'
    end
  end
  
  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    
    redirect_to companies_path
  end
  
  
  private
  def company_params
    params.require(:company).permit(:name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
<% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited
        this company from being saved:</h2>
      <ul>
        <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/companies/edit.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Company Listing</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>
  
  <% @companies.each do |company| %>
    <tr>
      <td><%=link_to company.name, company %> </td>
      <td><%= link_to 'Edit', edit_company_path(company) %></td>
      <td><%= link_to 'Delete', company_path(company),
          method: :delete, data: { confirm: 'Are You Sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p>
  <strong>Company:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tmsg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>